airflow:
  fernetKey: "j0PNE8131Vx-ix7BsNDwskFUlnLa00mWU17BRujVcdY="
  image:
    repository: puckel/docker-airflow
    tag: 1.10.3
  connections:
  # - id: my_aws
  #   type: aws
  #   extra: '{"aws_access_key_id": "**********", "aws_secret_access_key": "***", "region_name":"eu-central-1"}'
  - id: slack
    type: http
    host: 'https://hooks.slack.com/services'
    password: '/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'

workers:
  enabled: true
  replicas: 2
  celery:
    instances: 1

ingress:
  enabled: true
  web:
    host: "airflow.local"

  flower:
    host: "flower.local"

dags:
  doNotPickle: false
  git:
    url: https://github.com/burakince/airflow-dag-examples.git
    ref: master

  initContainer:
    enabled: true
